package com.pfe.domain.enums;


/**
 * Notification trigger enumeration.
 */
public enum NotificationTrigger {

  PROJECT_CREATION,
  ASSIGNMENT_TO_TASK,
  CHANGING_TASK_STATUS,
  REACHED_DEADLINE,
  VALIDATION_REQUEST_RECEIVED,
  SUSPICIOUS_CONNECTION_DETECTED,
  SYSTEM_UPDATE_SUCCESSFUL,
  CRITICAL_SYSTEM_ERROR,
  COMMENT_ADDED_TO_TASK,
  NEW_MEMBER_ADDED_TO_GROUP,
  UPDATE_PERMISSIONS,
  INIT_PERMISSIONS
}
