package com.pfe.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventNotificationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventNotificationAllPropertiesEquals(EventNotification expected, EventNotification actual) {
        assertEventNotificationAutoGeneratedPropertiesEquals(expected, actual);
        assertEventNotificationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventNotificationAllUpdatablePropertiesEquals(EventNotification expected, EventNotification actual) {
        assertEventNotificationUpdatableFieldsEquals(expected, actual);
        assertEventNotificationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventNotificationAutoGeneratedPropertiesEquals(EventNotification expected, EventNotification actual) {
        assertThat(expected)
            .as("Verify EventNotification auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventNotificationUpdatableFieldsEquals(EventNotification expected, EventNotification actual) {
        assertThat(expected)
            .as("Verify EventNotification relevant properties")
            .satisfies(e -> assertThat(e.getTaskId()).as("check taskId").isEqualTo(actual.getTaskId()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventNotificationUpdatableRelationshipsEquals(EventNotification expected, EventNotification actual) {
        assertThat(expected)
            .as("Verify EventNotification relationships")
            .satisfies(e -> assertThat(e.getNotification()).as("check notification").isEqualTo(actual.getNotification()));
    }
}
