package com.pfe.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificationPushedAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationPushedAllPropertiesEquals(NotificationPushed expected, NotificationPushed actual) {
        assertNotificationPushedAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationPushedAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationPushedAllUpdatablePropertiesEquals(NotificationPushed expected, NotificationPushed actual) {
        assertNotificationPushedUpdatableFieldsEquals(expected, actual);
        assertNotificationPushedUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationPushedAutoGeneratedPropertiesEquals(NotificationPushed expected, NotificationPushed actual) {
        assertThat(expected)
            .as("Verify NotificationPushed auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationPushedUpdatableFieldsEquals(NotificationPushed expected, NotificationPushed actual) {
        assertThat(expected)
            .as("Verify NotificationPushed relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getMessage()).as("check message").isEqualTo(actual.getMessage()))
            .satisfies(e -> assertThat(e.getNotificationDate()).as("check notificationDate").isEqualTo(actual.getNotificationDate()))
            .satisfies(e -> assertThat(e.getRecipientId()).as("check recipientId").isEqualTo(actual.getRecipientId()))
            .satisfies(e -> assertThat(e.getIsSeen()).as("check isSeen").isEqualTo(actual.getIsSeen()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationPushedUpdatableRelationshipsEquals(NotificationPushed expected, NotificationPushed actual) {}
}
