package com.pfe.Validator;

public class ValidationConstants {

    public static final String NAME_ALREADY_EXISTS = "NAME_ALREADY_EXISTS";
    public static final String NAME_MANDATORY = "NAME_MANDATORY";
    public static final String DESCRIPTION_MANDATORY = "DESCRIPTION_MANDATORY";
    public static final String DESCRIPTION_TOO_LONG = "DESCRIPTION_TOO_LONG";
    public static final String DESTINATIONS_MANDATORY = "DESTINATIONS_MANDATORY";
    public static final String FREQUENCIES_MUST_BE_NULL = "FREQUENCIES_MUST_BE_NULL";
    public static final String FREQUENCIES_MUST_NOT_BE_EMPTY = "FREQUENCIES_MUST_NOT_BE_EMPTY";
    public static final String FILE_PRESENT_FOR_PUSHED_NOTIFICATION = "FILE_PRESENT_FOR_PUSHED_NOTIFICATION";
    public static final String START_DATE_IS_BEFORE_NOW = "START_DATE_IS_BEFORE_NOW";
    public static final String END_DATE_IS_EQUAL_NOW = "END_DATE_IS_EQUAL_NOW";
    public static final String END_DATE_IS_EQUAL_START_DATE = "END_DATE_IS_EQUAL_START_DATE";
    public static final String TIMING_DOES_NOT_MATCH_HOUR_FORMAT = "TIMING_DOES_NOT_MATCH_HOUR_FORMAT";
    public static final String NO_DAYS_PRESENT_FOR_WEEKLY_NOTIFICATION = "NO_DAYS_PRESENT_FOR_WEEKLY_NOTIFICATION";
    public static final String START_DATE_SHOULD_NOT_BE_NULL_IN_DAILY_NOTIFICATION = "START_DATE_SHOULD_NOT_BE_NULL_IN_DAILY_NOTIFICATION";
    public static final String END_DATE_SHOULD_NOT_BE_NULL_IN_DAILY_NOTIFICATION = "END_DATE_SHOULD_NOT_BE_NULL_IN_DAILY_NOTIFICATION";
    public static final String DAYS_PRESENT_FOR_NON_WEEKLY_NOTIFICATION = "DAYS_PRESENT_FOR_NON_WEEKLY_NOTIFICATION";
    public static final String START_DATE_SHOULD_NOT_BE_NULL_IN_CUSTOM_NOTIFICATION = "START_DATE_SHOULD_NOT_BE_NULL_IN_CUSTOM_NOTIFICATION";
    public static final String INVALID_TIMING_FOR_NOTIFICATION_PER_MINUTE = "INVALID_TIMING_FOR_NOTIFICATION_PER_MINUTE";
    public static final String START_DATE_MUST_BE_NULL_IN_WEEKLY_NOTIFICATION = "START_DATE_MUST_BE_NULL_IN_WEEKLY_NOTIFICATION";
    public static final String END_DATE_MUST_BE_NULL_IN_WEEKLY_NOTIFICATION = "END_DATE_MUST_BE_NULL_IN_WEEKLY_NOTIFICATION";
    public static final String IS_REPEAT_SHOULD_BE_FALSE_IN_CUSTOM_NOTIFICATION = "IS_REPEAT_SHOULD_BE_FALSE_IN_CUSTOM_NOTIFICATION";
    public static final String IS_REPEAT_SHOULD_BE_TRUE_IN_DAILY_NOTIFICATION = "IS_REPEAT_SHOULD_BE_TRUE_IN_DAILY_NOTIFICATION";
    public static final String START_DATES_SHOULD_BE_DIFFERENT_IN_CUSTOM_NOTIFICATION = "START_DATES_SHOULD_BE_DIFFERENT_IN_CUSTOM_NOTIFICATION";

    public static final String START_DATE_IS_AFTER_END_DATE = "START_DATE_IS_AFTER_END_DATE";
    public static final String USER_NOT_FOUND = "USER_NOT_FOUND";
    public static final String ROLE_NOT_FOUND = "ROLE_NOT_FOUND";
    public static final String GROUP_NOT_FOUND = "GROUP_NOT_FOUND";
    public static final String DESTINATIONS_NOT_ALLOWED = "DESTINATIONS_NOT_ALLOWED";
    public static final String DESTINATION_TYPE_NOT_ALLOWED = "DESTINATION_TYPE_NOT_ALLOWED";
}
