spring:
  application:
    name: bs_gateway
  security:
    oauth2:
      client:
        login-user-admin: admin
        password-user-admin: pass
        provider:
          oidc:
            issuer-uri: http://localhost:8080/realms/bsrealm
        registration:
          oidc:
            client-id: bs_client
            client-secret: quT1y21Fwf1bAHrV7DprSGuPWtcsUpTE
            scope: openid, profile, email # last one for refresh tokens

  kafka:
    consumer:
      bootstrap-servers: localhost:9092

  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: BSUserManagement
          uri: http://localhost:8082
          predicates:
            - Method=GET, POST, PUT, DELETE, OPTIONS
            - Path=/user-management/**
        - id: BSWorkflowManagement
          uri: http://localhost:8083
          predicates:
            - Method=GET, POST, PUT, DELETE, OPTIONS
            - Path=/workflow-management/**
        - id: BSNotificationManagement
          uri: http://localhost:8084
          predicates:
            - Method=GET, POST, PUT, DELETE, OPTIONS
            - Path=/notification-management/**
        - id: BSReportManagement
          uri: http://localhost:8085
          predicates:
            - Method=GET, POST, PUT, DELETE, OPTIONS
            - Path=/report-management/**
        - id: BSFileManagement
          uri: http://localhost:8086
          predicates:
            - Method=GET, POST, PUT, DELETE, OPTIONS
            - Path=/file-management/**
        - id: BSFormManagement
          uri: http://localhost:8087
          predicates:
            - Method=GET, POST, PUT, DELETE, OPTIONS
            - Path=/form-management/**
        - id: BSConnectorManagement
          uri: http://localhost:8088
          predicates:
            - Method=GET, POST, PUT, DELETE, OPTIONS
            - Path=/connector-management/**
        - id: BSAuditManagement
          uri: http://localhost:8089
          predicates:
            - Method=GET, POST, PUT, DELETE, OPTIONS
            - Path=/audit-management/**
        - id: BSPayment
          uri: http://localhost:8090
          predicates:
            - Method=GET, POST, PUT, DELETE, OPTIONS
            - Path=/payment-management/**

application:
  origins: "http://localhost:4200"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

tokenvalidator:
  security:
    url_auth_server: http://localhost:8080/
    cache_token_delay: 60
    cache_certs_keys_delay: 600

keycloak:
  realm: bsrealm
  auth-server-url: http://localhost:8080/
  ssl-required: external
  resource: bs_client
  credentials:
    secret: quT1y21Fwf1bAHrV7DprSGuPWtcsUpTE
  use-resource-role-mappings: true
  principal-attribute: preferred_username

bs:
  front-url: http://localhost:4200

endpoint:
  gateway: http://localhost:9999
  notification-management: http://localhost:8084

server:
  port: 9999

ehoweya:
  ehoweya-url: "https://193.95.63.241:8443"
  responseType : "code"
  clientId : "bb537508-db77-476f-86b0-d26376e5d4ee"
  scope : "profile_fr given_name_fr family_name_fr gender identity birthdate address phone name given_name openid email profile"
  redirectUri : "https://www.esprit.tn"
  codeChallengeMethod : "S256"
  grantType : "authorization_code"
  clientSecret : "secret"

bs-app:
  keycloak:
    realm: bsrealm
    auth-server-url: http://localhost:8080/
    ssl-required: external
    resource: bs_client
    credentials:
      secret: quT1y21Fwf1bAHrV7DprSGuPWtcsUpTE
    use-resource-role-mappings: true
    principal-attribute: preferred_username

  keycloak-admin:
    username: bs_root
    password: Numeryx@2024!*
  #  username: admin
  #  password: pass

  endpoint:
    gateway-url: http://localhost:9999
    front-url: http://localhost:4200
    external-api-url: http://localhost:8088

