# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZGZhZGY1ZTcwZWRmNTdjNDgwYWVlYjJmNmRhMjEwNmJlY2M4NjhlNmM3MzYyMGE5YzUzMmQ1OTJjNjY0ZWJkYWE0NjlmNzEwNjVjODBmMTY5YjIxNGE3Njc5MzhkN2EyNTk5NzU2MWNjMjkyYzUyZTVlNDQ4M2FlZjk2Yzg1NTA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
