# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: M2I3Y2RlNWU5NDg2MjExNDMwODVhYjIyZjU0Y2JlZjUxOGJkMTg2NzdiMGY5Yjk3OTI4MDE3ZTliYTI4NzZmY2IxOWUyZDdhZTNjZGIwODkxNzY0NzYxZTJkODE2ZGFmYmM0YTU0NzQ1OTViY2MyNzkwNDk4MDgxNjU2YTc5N2I=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
