export const  NationalityList = [
  { code: 'AF', label: 'Afghanistan', flagClass: 'flag-icon-af', phonePrefix: '+93' },
  { code: 'AL', label: 'Albania', flagClass: 'flag-icon-al', phonePrefix: '+355' },
  { code: 'DZ', label: 'Algeria', flagClass: 'flag-icon-dz', phonePrefix: '+213' },
  { code: 'AS', label: 'American Samoa', flagClass: 'flag-icon-as', phonePrefix: '+1684' },
  { code: 'AD', label: 'Andorra', flagClass: 'flag-icon-ad', phonePrefix: '+376' },
  { code: 'AO', label: 'Angola', flagClass: 'flag-icon-ao', phonePrefix: '+244' },
  { code: 'AI', label: 'Anguilla', flagClass: 'flag-icon-ai', phonePrefix: '+1264' },
  { code: 'AQ', label: 'Antarctica', flagClass: 'flag-icon-aq', phonePrefix: '+672' },
  { code: 'AG', label: 'Antigua and Barbuda', flagClass: 'flag-icon-ag', phonePrefix: '+1268' },
  { code: 'AR', label: 'Argentina', flagClass: 'flag-icon-ar', phonePrefix: '+54' },
  { code: 'AM', label: 'Armenia', flagClass: 'flag-icon-am', phonePrefix: '+374' },
//  { code: 'AW', label: 'Aruba', flagClass: 'flag-icon-aw', phonePrefix: '+297' },
  { code: 'AU', label: 'Australia', flagClass: 'flag-icon-au', phonePrefix: '+61' },
  { code: 'AT', label: 'Austria', flagClass: 'flag-icon-at', phonePrefix: '+43' },
  { code: 'AZ', label: 'Azerbaijan', flagClass: 'flag-icon-az', phonePrefix: '+994' },
  { code: 'BS', label: 'Bahamas', flagClass: 'flag-icon-bs', phonePrefix: '+1242' },
  { code: 'BH', label: 'Bahrain', flagClass: 'flag-icon-bh', phonePrefix: '+973' },
  { code: 'BD', label: 'Bangladesh', flagClass: 'flag-icon-bd', phonePrefix: '+880' },
  { code: 'BB', label: 'Barbados', flagClass: 'flag-icon-bb', phonePrefix: '+1246' },
  { code: 'BY', label: 'Belarus', flagClass: 'flag-icon-by', phonePrefix: '+375' },
  { code: 'BE', label: 'Belgium', flagClass: 'flag-icon-be', phonePrefix: '+32' },
  { code: 'BZ', label: 'Belize', flagClass: 'flag-icon-bz', phonePrefix: '+501' },
  { code: 'BJ', label: 'Benin', flagClass: 'flag-icon-bj', phonePrefix: '+229' },
  //{ code: 'BM', label: 'Bermuda', flagClass: 'flag-icon-bm', phonePrefix: '+1441' },
  { code: 'BT', label: 'Bhutan', flagClass: 'flag-icon-bt', phonePrefix: '+975' },
  { code: 'BO', label: 'Bolivia', flagClass: 'flag-icon-bo', phonePrefix: '+591' },
  { code: 'BA', label: 'Bosnia and Herzegovina', flagClass: 'flag-icon-ba', phonePrefix: '+387' },
  { code: 'BW', label: 'Botswana', flagClass: 'flag-icon-bw', phonePrefix: '+267' },
  { code: 'BR', label: 'Brazil', flagClass: 'flag-icon-br', phonePrefix: '+55' },
  { code: 'BN', label: 'Brunei', flagClass: 'flag-icon-bn', phonePrefix: '+673' },
  { code: 'BG', label: 'Bulgaria', flagClass: 'flag-icon-bg', phonePrefix: '+359' },
  { code: 'BF', label: 'Burkina Faso', flagClass: 'flag-icon-bf', phonePrefix: '+226' },
  { code: 'BI', label: 'Burundi', flagClass: 'flag-icon-bi', phonePrefix: '+257' },
  { code: 'CV', label: 'Cabo Verde', flagClass: 'flag-icon-cv', phonePrefix: '+238' },
  { code: 'KH', label: 'Cambodia', flagClass: 'flag-icon-kh', phonePrefix: '+855' },
  { code: 'CM', label: 'Cameroon', flagClass: 'flag-icon-cm', phonePrefix: '+237' },
  { code: 'CA', label: 'Canada', flagClass: 'flag-icon-ca', phonePrefix: '+1' },
  { code: 'CF', label: 'Central African Republic', flagClass: 'flag-icon-cf', phonePrefix: '+236' },
  { code: 'TD', label: 'Chad', flagClass: 'flag-icon-td', phonePrefix: '+235' },
  { code: 'CL', label: 'Chile', flagClass: 'flag-icon-cl', phonePrefix: '+56' },
  { code: 'CN', label: 'China', flagClass: 'flag-icon-cn', phonePrefix: '+86' },
  { code: 'CO', label: 'Colombia', flagClass: 'flag-icon-co', phonePrefix: '+57' },
  { code: 'KM', label: 'Comoros', flagClass: 'flag-icon-km', phonePrefix: '+269' },
  { code: 'CG', label: 'Congo', flagClass: 'flag-icon-cg', phonePrefix: '+242' },
  { code: 'CD', label: 'Congo (DRC)', flagClass: 'flag-icon-cd', phonePrefix: '+243' },
  { code: 'CR', label: 'Costa Rica', flagClass: 'flag-icon-cr', phonePrefix: '+506' },
  { code: 'HR', label: 'Croatia', flagClass: 'flag-icon-hr', phonePrefix: '+385' },
  { code: 'CU', label: 'Cuba', flagClass: 'flag-icon-cu', phonePrefix: '+53' },
  { code: 'CY', label: 'Cyprus', flagClass: 'flag-icon-cy', phonePrefix: '+357' },
  { code: 'CZ', label: 'Czech Republic', flagClass: 'flag-icon-cz', phonePrefix: '+420' },
  { code: 'DK', label: 'Denmark', flagClass: 'flag-icon-dk', phonePrefix: '+45' },
  { code: 'DJ', label: 'Djibouti', flagClass: 'flag-icon-dj', phonePrefix: '+253' },
  { code: 'DM', label: 'Dominica', flagClass: 'flag-icon-dm', phonePrefix: '+1767' },
  { code: 'DO', label: 'Dominican Republic', flagClass: 'flag-icon-do', phonePrefix: '+1-809' },
  { code: 'EC', label: 'Ecuador', flagClass: 'flag-icon-ec', phonePrefix: '+593' },
  { code: 'EG', label: 'Egypt', flagClass: 'flag-icon-eg', phonePrefix: '+20' },
  { code: 'SV', label: 'El Salvador', flagClass: 'flag-icon-sv', phonePrefix: '+503' },
  { code: 'GQ', label: 'Equatorial Guinea', flagClass: 'flag-icon-gq', phonePrefix: '+240' },
  { code: 'ER', label: 'Eritrea', flagClass: 'flag-icon-er', phonePrefix: '+291' },
  { code: 'EE', label: 'Estonia', flagClass: 'flag-icon-ee', phonePrefix: '+372' },
  { code: 'SZ', label: 'Eswatini', flagClass: 'flag-icon-sz', phonePrefix: '+268' },
  { code: 'ET', label: 'Ethiopia', flagClass: 'flag-icon-et', phonePrefix: '+251' },
  { code: 'FJ', label: 'Fiji', flagClass: 'flag-icon-fj', phonePrefix: '+679' },
  { code: 'FI', label: 'Finland', flagClass: 'flag-icon-fi', phonePrefix: '+358' },
  { code: 'FR', label: 'France', flagClass: 'flag-icon-fr', phonePrefix: '+33' },
  { code: 'GA', label: 'Gabon', flagClass: 'flag-icon-ga', phonePrefix: '+241' },
  { code: 'GM', label: 'Gambia', flagClass: 'flag-icon-gm', phonePrefix: '+220' },
  { code: 'GE', label: 'Georgia', flagClass: 'flag-icon-ge', phonePrefix: '+995' },
  { code: 'DE', label: 'Germany', flagClass: 'flag-icon-de', phonePrefix: '+49' },
  { code: 'HT', label: 'Haiti', flagClass: 'flag-icon-ht', phonePrefix: '+509' },
  { code: 'HN', label: 'Honduras', flagClass: 'flag-icon-hn', phonePrefix: '+504' },
  { code: 'HK', label: 'Hong Kong', flagClass: 'flag-icon-hk', phonePrefix: '+852' },
  { code: 'HU', label: 'Hungary', flagClass: 'flag-icon-hu', phonePrefix: '+36' },
  { code: 'IS', label: 'Iceland', flagClass: 'flag-icon-is', phonePrefix: '+354' },
  { code: 'IN', label: 'India', flagClass: 'flag-icon-in', phonePrefix: '+91' },
  { code: 'ID', label: 'Indonesia', flagClass: 'flag-icon-id', phonePrefix: '+62' },
  { code: 'IR', label: 'Iran', flagClass: 'flag-icon-ir', phonePrefix: '+98' },
  { code: 'IQ', label: 'Iraq', flagClass: 'flag-icon-iq', phonePrefix: '+964' },
  { code: 'IE', label: 'Ireland', flagClass: 'flag-icon-ie', phonePrefix: '+353' },
  { code: 'IT', label: 'Italy', flagClass: 'flag-icon-it', phonePrefix: '+39' },
  { code: 'CI', label: 'Ivory Coast', flagClass: 'flag-icon-ci', phonePrefix: '+225' },
  { code: 'JM', label: 'Jamaica', flagClass: 'flag-icon-jm', phonePrefix: '+1876' },
  { code: 'JP', label: 'Japan', flagClass: 'flag-icon-jp', phonePrefix: '+81' },
  { code: 'JO', label: 'Jordan', flagClass: 'flag-icon-jo', phonePrefix: '+962' },
  { code: 'KZ', label: 'Kazakhstan', flagClass: 'flag-icon-kz', phonePrefix: '+7' },
  { code: 'KE', label: 'Kenya', flagClass: 'flag-icon-ke', phonePrefix: '+254' },
  { code: 'KI', label: 'Kiribati', flagClass: 'flag-icon-ki', phonePrefix: '+686' },
  { code: 'KW', label: 'Kuwait', flagClass: 'flag-icon-kw', phonePrefix: '+965' },
  { code: 'KG', label: 'Kyrgyzstan', flagClass: 'flag-icon-kg', phonePrefix: '+996' },
  { code: 'LA', label: 'Laos', flagClass: 'flag-icon-la', phonePrefix: '+856' },
  { code: 'LV', label: 'Latvia', flagClass: 'flag-icon-lv', phonePrefix: '+371' },
  { code: 'LB', label: 'Lebanon', flagClass: 'flag-icon-lb', phonePrefix: '+961' },
  { code: 'LS', label: 'Lesotho', flagClass: 'flag-icon-ls', phonePrefix: '+266' },
  { code: 'LR', label: 'Liberia', flagClass: 'flag-icon-lr', phonePrefix: '+231' },
  { code: 'LY', label: 'Libya', flagClass: 'flag-icon-ly', phonePrefix: '+218' },
  { code: 'LI', label: 'Liechtenstein', flagClass: 'flag-icon-li', phonePrefix: '+423' },
  { code: 'LT', label: 'Lithuania', flagClass: 'flag-icon-lt', phonePrefix: '+370' },
  { code: 'LU', label: 'Luxembourg', flagClass: 'flag-icon-lu', phonePrefix: '+352' },
  { code: 'MO', label: 'Macau', flagClass: 'flag-icon-mo', phonePrefix: '+853' },
  { code: 'MK', label: 'North Macedonia', flagClass: 'flag-icon-mk', phonePrefix: '+389' },
  { code: 'MG', label: 'Madagascar', flagClass: 'flag-icon-mg', phonePrefix: '+261' },
  { code: 'MW', label: 'Malawi', flagClass: 'flag-icon-mw', phonePrefix: '+265' },
  { code: 'MY', label: 'Malaysia', flagClass: 'flag-icon-my', phonePrefix: '+60' },
  { code: 'MV', label: 'Maldives', flagClass: 'flag-icon-mv', phonePrefix: '+960' },
  { code: 'ML', label: 'Mali', flagClass: 'flag-icon-ml', phonePrefix: '+223' },
  { code: 'MT', label: 'Malta', flagClass: 'flag-icon-mt', phonePrefix: '+356' },
  { code: 'MH', label: 'Marshall Islands', flagClass: 'flag-icon-mh', phonePrefix: '+692' },
  { code: 'MQ', label: 'Martinique', flagClass: 'flag-icon-mq', phonePrefix: '+596' },
  { code: 'MR', label: 'Mauritania', flagClass: 'flag-icon-mr', phonePrefix: '+222' },
  { code: 'MU', label: 'Mauritius', flagClass: 'flag-icon-mu', phonePrefix: '+230' },
  { code: 'YT', label: 'Mayotte', flagClass: 'flag-icon-yt', phonePrefix: '+262' },
  { code: 'MX', label: 'Mexico', flagClass: 'flag-icon-mx', phonePrefix: '+52' },
  { code: 'FM', label: 'Micronesia', flagClass: 'flag-icon-fm', phonePrefix: '+691' },
  { code: 'MD', label: 'Moldova', flagClass: 'flag-icon-md', phonePrefix: '+373' },
  { code: 'MC', label: 'Monaco', flagClass: 'flag-icon-mc', phonePrefix: '+377' },
  { code: 'MN', label: 'Mongolia', flagClass: 'flag-icon-mn', phonePrefix: '+976' },
  { code: 'ME', label: 'Montenegro', flagClass: 'flag-icon-me', phonePrefix: '+382' },
  { code: 'MS', label: 'Montserrat', flagClass: 'flag-icon-ms', phonePrefix: '+1664' },
  { code: 'MA', label: 'Morocco', flagClass: 'flag-icon-ma', phonePrefix: '+212' },
  { code: 'MZ', label: 'Mozambique', flagClass: 'flag-icon-mz', phonePrefix: '+258' },
  { code: 'MM', label: 'Myanmar (Burma)', flagClass: 'flag-icon-mm', phonePrefix: '+95' },
  { code: 'NA', label: 'Namibia', flagClass: 'flag-icon-na', phonePrefix: '+264' },
  { code: 'NR', label: 'Nauru', flagClass: 'flag-icon-nr', phonePrefix: '+674' },
  { code: 'NP', label: 'Nepal', flagClass: 'flag-icon-np', phonePrefix: '+977' },
  { code: 'NL', label: 'Netherlands', flagClass: 'flag-icon-nl', phonePrefix: '+31' },
  { code: 'NC', label: 'New Caledonia', flagClass: 'flag-icon-nc', phonePrefix: '+687' },
  { code: 'NZ', label: 'New Zealand', flagClass: 'flag-icon-nz', phonePrefix: '+64' },
  { code: 'NI', label: 'Nicaragua', flagClass: 'flag-icon-ni', phonePrefix: '+505' },
  { code: 'NE', label: 'Niger', flagClass: 'flag-icon-ne', phonePrefix: '+227' },
  { code: 'NG', label: 'Nigeria', flagClass: 'flag-icon-ng', phonePrefix: '+234' },
  { code: 'KP', label: 'North Korea', flagClass: 'flag-icon-kp', phonePrefix: '+850' },
  { code: 'MP', label: 'Northern Mariana Islands', flagClass: 'flag-icon-mp', phonePrefix: '+1670' },
  { code: 'NO', label: 'Norway', flagClass: 'flag-icon-no', phonePrefix: '+47' },
  { code: 'OM', label: 'Oman', flagClass: 'flag-icon-om', phonePrefix: '+968' },
  { code: 'PK', label: 'Pakistan', flagClass: 'flag-icon-pk', phonePrefix: '+92' },
  { code: 'PW', label: 'Palau', flagClass: 'flag-icon-pw', phonePrefix: '+680' },
  { code: 'PA', label: 'Panama', flagClass: 'flag-icon-pa', phonePrefix: '+507' },
  { code: 'PG', label: 'Papua New Guinea', flagClass: 'flag-icon-pg', phonePrefix: '+675' },
  { code: 'PY', label: 'Paraguay', flagClass: 'flag-icon-py', phonePrefix: '+595' },
  { code: 'PE', label: 'Peru', flagClass: 'flag-icon-pe', phonePrefix: '+51' },
  { code: 'PH', label: 'Philippines', flagClass: 'flag-icon-ph', phonePrefix: '+63' },
  { code: 'PL', label: 'Poland', flagClass: 'flag-icon-pl', phonePrefix: '+48' },
  { code: 'PT', label: 'Portugal', flagClass: 'flag-icon-pt', phonePrefix: '+351' },
  { code: 'PR', label: 'Puerto Rico', flagClass: 'flag-icon-pr', phonePrefix: '+1' },
  { code: 'QA', label: 'Qatar', flagClass: 'flag-icon-qa', phonePrefix: '+974' },
 // { code: 'RE', label: 'Réunion', flagClass: 'flag-icon-re', phonePrefix: '+262' },
  { code: 'RO', label: 'Romania', flagClass: 'flag-icon-ro', phonePrefix: '+40' },
  { code: 'RU', label: 'Russia', flagClass: 'flag-icon-ru', phonePrefix: '+7' },
  { code: 'RW', label: 'Rwanda', flagClass: 'flag-icon-rw', phonePrefix: '+250' },
  { code: 'BL', label: 'Saint Barthélemy', flagClass: 'flag-icon-bl', phonePrefix: '+590' },
  { code: 'SH', label: 'Saint Helena', flagClass: 'flag-icon-sh', phonePrefix: '+290' },
  { code: 'KN', label: 'Saint Kitts and Nevis', flagClass: 'flag-icon-kn', phonePrefix: '+1' },
  { code: 'LC', label: 'Saint Lucia', flagClass: 'flag-icon-lc', phonePrefix: '+1' },
  { code: 'MF', label: 'Saint Martin', flagClass: 'flag-icon-mf', phonePrefix: '+590' },
  { code: 'PM', label: 'Saint Pierre and Miquelon', flagClass: 'flag-icon-pm', phonePrefix: '+508' },
  { code: 'VC', label: 'Saint Vincent and the Grenadines', flagClass: 'flag-icon-vc', phonePrefix: '+1' },
  { code: 'WS', label: 'Samoa', flagClass: 'flag-icon-ws', phonePrefix: '+685' },
  { code: 'SM', label: 'San Marino', flagClass: 'flag-icon-sm', phonePrefix: '+378' },
  { code: 'ST', label: 'São Tomé and Príncipe', flagClass: 'flag-icon-st', phonePrefix: '+239' },
  { code: 'SA', label: 'Saudi Arabia', flagClass: 'flag-icon-sa', phonePrefix: '+966' },
  { code: 'SN', label: 'Senegal', flagClass: 'flag-icon-sn', phonePrefix: '+221' },
  { code: 'RS', label: 'Serbia', flagClass: 'flag-icon-rs', phonePrefix: '+381' },
  { code: 'SC', label: 'Seychelles', flagClass: 'flag-icon-sc', phonePrefix: '+248' },
  { code: 'SL', label: 'Sierra Leone', flagClass: 'flag-icon-sl', phonePrefix: '+232' },
  { code: 'SG', label: 'Singapore', flagClass: 'flag-icon-sg', phonePrefix: '+65' },
  { code: 'SX', label: 'Sint Maarten', flagClass: 'flag-icon-sx', phonePrefix: '+1' },
  { code: 'SK', label: 'Slovakia', flagClass: 'flag-icon-sk', phonePrefix: '+421' },
  { code: 'SI', label: 'Slovenia', flagClass: 'flag-icon-si', phonePrefix: '+386' },
  { code: 'SB', label: 'Solomon Islands', flagClass: 'flag-icon-sb', phonePrefix: '+677' },
  { code: 'SO', label: 'Somalia', flagClass: 'flag-icon-so', phonePrefix: '+252' },
  { code: 'ZA', label: 'South Africa', flagClass: 'flag-icon-za', phonePrefix: '+27' },
  { code: 'GS', label: 'South Georgia and the South Sandwich Islands', flagClass: 'flag-icon-gs', phonePrefix: '+500' },
  { code: 'KR', label: 'South Korea', flagClass: 'flag-icon-kr', phonePrefix: '+82' },
  { code: 'SS', label: 'South Sudan', flagClass: 'flag-icon-ss', phonePrefix: '+211' },
  { code: 'ES', label: 'Spain', flagClass: 'flag-icon-es', phonePrefix: '+34' },
  { code: 'LK', label: 'Sri Lanka', flagClass: 'flag-icon-lk', phonePrefix: '+94' },
  { code: 'SD', label: 'Sudan', flagClass: 'flag-icon-sd', phonePrefix: '+249' },
  { code: 'SR', label: 'Suriname', flagClass: 'flag-icon-sr', phonePrefix: '+597' },
  { code: 'SJ', label: 'Svalbard and Jan Mayen', flagClass: 'flag-icon-sj', phonePrefix: '+47' },
  { code: 'SZ', label: 'Swaziland', flagClass: 'flag-icon-sz', phonePrefix: '+268' },
  { code: 'SE', label: 'Sweden', flagClass: 'flag-icon-se', phonePrefix: '+46' },
  { code: 'CH', label: 'Switzerland', flagClass: 'flag-icon-ch', phonePrefix: '+41' },
  { code: 'SY', label: 'Syria', flagClass: 'flag-icon-sy', phonePrefix: '+963' },
  { code: 'TW', label: 'Taiwan', flagClass: 'flag-icon-tw', phonePrefix: '+886' },
  { code: 'TJ', label: 'Tajikistan', flagClass: 'flag-icon-tj', phonePrefix: '+992' },
  { code: 'TZ', label: 'Tanzania', flagClass: 'flag-icon-tz', phonePrefix: '+255' },
  { code: 'TH', label: 'Thailand', flagClass: 'flag-icon-th', phonePrefix: '+66' },
 // { code: 'TL', label: 'Timor-Leste', flagClass: 'flag-icon-tl', phonePrefix: '+670' },
  { code: 'TG', label: 'Togo', flagClass: 'flag-icon-tg', phonePrefix: '+228' },
  { code: 'TK', label: 'Tokelau', flagClass: 'flag-icon-tk', phonePrefix: '+690' },
  { code: 'TO', label: 'Tonga', flagClass: 'flag-icon-to', phonePrefix: '+676' },
  { code: 'TT', label: 'Trinidad and Tobago', flagClass: 'flag-icon-tt', phonePrefix: '+1' },
  { code: 'TN', label: 'Tunisia', flagClass: 'flag-icon-tn', phonePrefix: '+216' },
  { code: 'TR', label: 'Turkey', flagClass: 'flag-icon-tr', phonePrefix: '+90' },
  { code: 'TM', label: 'Turkmenistan', flagClass: 'flag-icon-tm', phonePrefix: '+993' },
  { code: 'TC', label: 'Turks and Caicos Islands', flagClass: 'flag-icon-tc', phonePrefix: '+1' },
  { code: 'TV', label: 'Tuvalu', flagClass: 'flag-icon-tv', phonePrefix: '+688' },
  { code: 'UG', label: 'Uganda', flagClass: 'flag-icon-ug', phonePrefix: '+256' },
  { code: 'UA', label: 'Ukraine', flagClass: 'flag-icon-ua', phonePrefix: '+380' },
  { code: 'AE', label: 'United Arab Emirates', flagClass: 'flag-icon-ae', phonePrefix: '+971' },
  { code: 'GB', label: 'United Kingdom', flagClass: 'flag-icon-gb', phonePrefix: '+44' },
  { code: 'US', label: 'United States', flagClass: 'flag-icon-us', phonePrefix: '+1' },
  { code: 'UY', label: 'Uruguay', flagClass: 'flag-icon-uy', phonePrefix: '+598' },
  { code: 'UZ', label: 'Uzbekistan', flagClass: 'flag-icon-uz', phonePrefix: '+998' },
  { code: 'VU', label: 'Vanuatu', flagClass: 'flag-icon-vu', phonePrefix: '+678' },
  { code: 'VE', label: 'Venezuela', flagClass: 'flag-icon-ve', phonePrefix: '+58' },
  { code: 'VN', label: 'Vietnam', flagClass: 'flag-icon-vn', phonePrefix: '+84' },
  { code: 'WF', label: 'Wallis and Futuna', flagClass: 'flag-icon-wf', phonePrefix: '+681' },
  { code: 'YE', label: 'Yemen', flagClass: 'flag-icon-ye', phonePrefix: '+967' },
  { code: 'ZM', label: 'Zambia', flagClass: 'flag-icon-zm', phonePrefix: '+260' },
  { code: 'ZW', label: 'Zimbabwe', flagClass: 'flag-icon-zw', phonePrefix: '+263' }
]
