
DELETE FROM "bs_designations_list"
WHERE pm_user_id = (SELECT id FROM bs_user WHERE username = 'pm-ext-1111221' LIMIT 1)
  AND designated_user_id = (SELECT id FROM bs_user WHERE username = 'ext-1111221' LIMIT 1)
  AND role_id = (SELECT id FROM bs_role WHERE label = 'BS_ROLE_PM_RESP_CTRL_QA' LIMIT 1);

DELETE FROM "bs_designations_list"
WHERE pm_user_id = (SELECT id FROM bs_user WHERE username = 'pm-ext-1111221' LIMIT 1)
AND designated_user_id = (SELECT id FROM bs_user WHERE username = 'ext-1111221' LIMIT 1)
AND role_id = (SELECT id FROM bs_role WHERE label = 'BS_ROLE_PM_RESP_REG_AFF' LIMIT 1);


INSERT INTO "bs_rel_user_role"("user_id", "role_id")
VALUES
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111225' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111226' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111227' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111228' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111229' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111230' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111231' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111232' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111233' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111234' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111235' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111236' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111237' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111238' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111239' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111240' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111241' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111242' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111243' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111244' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111245' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111246' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111247' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111248' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111249' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111250' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111251' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111252' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111253' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111254' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111255' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111256' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111257' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111258' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111259' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111260' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111261' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111262' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111263' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111264' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111265' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111266' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111267' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111268' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111269' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111270' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111271' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111272' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111273' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111274' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111275' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111276' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111277' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111278' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111279' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111280' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111281' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'ext-1111282' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111252' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111253' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111254' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111255' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111256' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111257' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111258' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111259' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111260' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111261' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111262' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111263' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111264' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111265' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111266' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111267' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111268' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111269' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111270' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111271' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111272' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111273' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111274' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111275' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111276' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111277' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111278' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111279' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111280' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111281' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111282' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111283' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111284' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111285' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111286' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111287' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111288' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111289' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111290' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111291' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111292' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111293' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1)),
    ((SELECT id FROM "bs_user" WHERE username = 'pm-ext-1111294' LIMIT 1), (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_ECTD' LIMIT 1));


DELETE FROM "bs_rel_user_role"
WHERE role_id = (SELECT id FROM "bs_role" WHERE label = 'BS_ROLE_PP_DEFAULT' LIMIT 1)
  AND user_id IN (
SELECT id FROM "bs_user"
WHERE username IN (
    'ext-1111225','ext-1111226','ext-1111227','ext-1111228','ext-1111229',
    'ext-1111230','ext-1111231','ext-1111232','ext-1111233','ext-1111234',
    'ext-1111235','ext-1111236','ext-1111237','ext-1111238','ext-1111239',
    'ext-1111240','ext-1111241','ext-1111242','ext-1111243','ext-1111244',
    'ext-1111245','ext-1111246','ext-1111247','ext-1111248','ext-1111249',
    'ext-1111250','ext-1111251','ext-1111252','ext-1111253','ext-1111254',
    'ext-1111255','ext-1111256','ext-1111257','ext-1111258','ext-1111259',
    'ext-1111260','ext-1111261','ext-1111262','ext-1111263','ext-1111264',
    'ext-1111265','ext-1111266','ext-1111267','ext-1111268','ext-1111269',
    'ext-1111270','ext-1111271','ext-1111272','ext-1111273','ext-1111274',
    'ext-1111275','ext-1111276','ext-1111277','ext-1111278','ext-1111279',
    'ext-1111280','ext-1111281','ext-1111282'
    ));
