package com.pfe.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConfigurationReportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigurationReportAllPropertiesEquals(ConfigurationReport expected, ConfigurationReport actual) {
        assertConfigurationReportAutoGeneratedPropertiesEquals(expected, actual);
        assertConfigurationReportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigurationReportAllUpdatablePropertiesEquals(ConfigurationReport expected, ConfigurationReport actual) {
        assertConfigurationReportUpdatableFieldsEquals(expected, actual);
        assertConfigurationReportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigurationReportAutoGeneratedPropertiesEquals(ConfigurationReport expected, ConfigurationReport actual) {
        assertThat(expected)
            .as("Verify ConfigurationReport auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigurationReportUpdatableFieldsEquals(ConfigurationReport expected, ConfigurationReport actual) {
        assertThat(expected)
            .as("Verify ConfigurationReport relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getAddress()).as("check address").isEqualTo(actual.getAddress()))
            .satisfies(e -> assertThat(e.getPostalCode()).as("check postalCode").isEqualTo(actual.getPostalCode()))
            .satisfies(e -> assertThat(e.getPhone()).as("check phone").isEqualTo(actual.getPhone()))
            .satisfies(e -> assertThat(e.getFax()).as("check fax").isEqualTo(actual.getFax()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getLogo()).as("check logo").isEqualTo(actual.getLogo()))
            .satisfies(e -> assertThat(e.getFooter()).as("check footer").isEqualTo(actual.getFooter()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigurationReportUpdatableRelationshipsEquals(ConfigurationReport expected, ConfigurationReport actual) {}
}
