package com.pfe.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReportTemplateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportTemplateAllPropertiesEquals(ReportTemplate expected, ReportTemplate actual) {
        assertReportTemplateAutoGeneratedPropertiesEquals(expected, actual);
        assertReportTemplateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportTemplateAllUpdatablePropertiesEquals(ReportTemplate expected, ReportTemplate actual) {
        assertReportTemplateUpdatableFieldsEquals(expected, actual);
        assertReportTemplateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportTemplateAutoGeneratedPropertiesEquals(ReportTemplate expected, ReportTemplate actual) {
        assertThat(expected)
            .as("Verify ReportTemplate auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportTemplateUpdatableFieldsEquals(ReportTemplate expected, ReportTemplate actual) {
        assertThat(expected)
            .as("Verify ReportTemplate relevant properties")
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getPath()).as("check path").isEqualTo(actual.getPath()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportTemplateUpdatableRelationshipsEquals(ReportTemplate expected, ReportTemplate actual) {}
}
